### ISSUE TITLE
any joy with angular2 ? :)

### ISSUE THREAD

**Issue by jetpackdata** [danialfarid/ngf-upload#1]

**Comment by danialfarid** [comment]
It is delayed could be 1-2 months.

**Comment by jetpackdata** [comment]
cool. thanks for the update.

**Comment by korvinko** [comment]
Do you have plans to work on it? Our project migrate to angular 4 and we missed so good upload component here

**Comment by chirag-sa** [comment]
It is 3 years now after the first commit.

**Comment by danialfarid** [comment]
I have very limited time now and there is no plan for completion of angular 2 version. Hoping someone would step up and pick it up the work on that branch and complete it or fork it.
